//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGI_Project_WebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Pages_IndexModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pages_IndexModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CGI_Project_WebApp.Resources.Pages.IndexModel", typeof(Pages_IndexModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add photos.
        /// </summary>
        public static string AddPhotoNav {
            get {
                return ResourceManager.GetString("AddPhotoNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add profile picture.
        /// </summary>
        public static string AddProfilePhoto {
            get {
                return ResourceManager.GetString("AddProfilePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote.
        /// </summary>
        public static string BtnVote {
            get {
                return ResourceManager.GetString("BtnVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excursion description.
        /// </summary>
        public static string ExcursionDescription {
            get {
                return ResourceManager.GetString("ExcursionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important info (e.g. bring sunglasses).
        /// </summary>
        public static string ExcursionInfo {
            get {
                return ResourceManager.GetString("ExcursionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excursion location.
        /// </summary>
        public static string ExcursionLocation {
            get {
                return ResourceManager.GetString("ExcursionLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excursion name.
        /// </summary>
        public static string ExcursionName {
            get {
                return ResourceManager.GetString("ExcursionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string FooterContactUs {
            get {
                return ResourceManager.GetString("FooterContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string FooterMore {
            get {
                return ResourceManager.GetString("FooterMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started.
        /// </summary>
        public static string HeroButton {
            get {
                return ResourceManager.GetString("HeroButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a suggestion.
        /// </summary>
        public static string HeroSubtitle {
            get {
                return ResourceManager.GetString("HeroSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Team Adventures: Building Bonds, One Excursion at a Time. Discover, Bond, and Thrive with Every Corporate Expedition!.
        /// </summary>
        public static string HeroTitle {
            get {
                return ResourceManager.GetString("HeroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LeaderboardName {
            get {
                return ResourceManager.GetString("LeaderboardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboard.
        /// </summary>
        public static string LeaderboardNav {
            get {
                return ResourceManager.GetString("LeaderboardNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string LeaderboardPosition {
            get {
                return ResourceManager.GetString("LeaderboardPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string LeaderboardScore {
            get {
                return ResourceManager.GetString("LeaderboardScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboard.
        /// </summary>
        public static string LeaderboardTitle {
            get {
                return ResourceManager.GetString("LeaderboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal.
        /// </summary>
        public static string Legal {
            get {
                return ResourceManager.GetString("Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail does not exist and/or server error.
        /// </summary>
        public static string ModelEmailErrorKey {
            get {
                return ResourceManager.GetString("ModelEmailErrorKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model state not correct.
        /// </summary>
        public static string ModelErrorKey {
            get {
                return ResourceManager.GetString("ModelErrorKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add suggestion. Suggestion might exist already.
        /// </summary>
        public static string ModelSuggestErrorKey {
            get {
                return ResourceManager.GetString("ModelSuggestErrorKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion added successfully.
        /// </summary>
        public static string ModelSuggestKey {
            get {
                return ResourceManager.GetString("ModelSuggestKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll.
        /// </summary>
        public static string NavPoll {
            get {
                return ResourceManager.GetString("NavPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add photo to album.
        /// </summary>
        public static string PhotoFormAdd {
            get {
                return ResourceManager.GetString("PhotoFormAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a description.
        /// </summary>
        public static string PhotoFormDesc {
            get {
                return ResourceManager.GetString("PhotoFormDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select photo or drag and drop.
        /// </summary>
        public static string PhotoFormLabel1 {
            get {
                return ResourceManager.GetString("PhotoFormLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop your file here, or click to select file.
        /// </summary>
        public static string PhotoFormLabel2 {
            get {
                return ResourceManager.GetString("PhotoFormLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo type is not valid, please select a valid photo.
        /// </summary>
        public static string PhotoInvalid {
            get {
                return ResourceManager.GetString("PhotoInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo has been added successfully.
        /// </summary>
        public static string PhotoSuccess {
            get {
                return ResourceManager.GetString("PhotoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo is too large, please select a smaller photo.
        /// </summary>
        public static string PhotoTooLarge {
            get {
                return ResourceManager.GetString("PhotoTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only select a maximum of 3 excursions.
        /// </summary>
        public static string PollAlert {
            get {
                return ResourceManager.GetString("PollAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll name.
        /// </summary>
        public static string PollName {
            get {
                return ResourceManager.GetString("PollName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No suggestions have been done, ask your employees to make suggestions.
        /// </summary>
        public static string PollNoSuggestions {
            get {
                return ResourceManager.GetString("PollNoSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the period in which employees can vote.
        /// </summary>
        public static string PollRange {
            get {
                return ResourceManager.GetString("PollRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll.
        /// </summary>
        public static string PollTitle {
            get {
                return ResourceManager.GetString("PollTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ProfileDescription {
            get {
                return ResourceManager.GetString("ProfileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string ProfileException {
            get {
                return ResourceManager.GetString("ProfileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string ProfileLocation {
            get {
                return ResourceManager.GetString("ProfileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No suggestions available.
        /// </summary>
        public static string ProfileNoSuggestions {
            get {
                return ResourceManager.GetString("ProfileNoSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No team information available.
        /// </summary>
        public static string ProfileNoTeam {
            get {
                return ResourceManager.GetString("ProfileNoTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string ProfileTeam {
            get {
                return ResourceManager.GetString("ProfileTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        public static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votes.
        /// </summary>
        public static string ProfileVotes {
            get {
                return ResourceManager.GetString("ProfileVotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Suggestions.
        /// </summary>
        public static string ProfileYourSuggestions {
            get {
                return ResourceManager.GetString("ProfileYourSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Excursions.
        /// </summary>
        public static string RecentTitle {
            get {
                return ResourceManager.GetString("RecentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a suggestion.
        /// </summary>
        public static string SelectPollSuggestion {
            get {
                return ResourceManager.GetString("SelectPollSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select photo.
        /// </summary>
        public static string SelectProfilePhoto {
            get {
                return ResourceManager.GetString("SelectProfilePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show photos.
        /// </summary>
        public static string ShowPhotoNav {
            get {
                return ResourceManager.GetString("ShowPhotoNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social media.
        /// </summary>
        public static string Social {
            get {
                return ResourceManager.GetString("Social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest.
        /// </summary>
        public static string SuggestNav {
            get {
                return ResourceManager.GetString("SuggestNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SuggestSubmit {
            get {
                return ResourceManager.GetString("SuggestSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill out the form below.
        /// </summary>
        public static string SuggestSubtitle {
            get {
                return ResourceManager.GetString("SuggestSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest an excursion.
        /// </summary>
        public static string SuggestTitle {
            get {
                return ResourceManager.GetString("SuggestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not vote.
        /// </summary>
        public static string VoteError {
            get {
                return ResourceManager.GetString("VoteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote.
        /// </summary>
        public static string VoteNav {
            get {
                return ResourceManager.GetString("VoteNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can vote for one excursion in each period.
        /// </summary>
        public static string VoteSubtitle {
            get {
                return ResourceManager.GetString("VoteSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully voted, submitted by.
        /// </summary>
        public static string VoteSuccess {
            get {
                return ResourceManager.GetString("VoteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote for an excursion.
        /// </summary>
        public static string VoteTitle {
            get {
                return ResourceManager.GetString("VoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome manager.
        /// </summary>
        public static string WelcomeManager {
            get {
                return ResourceManager.GetString("WelcomeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string WelcomeUser {
            get {
                return ResourceManager.GetString("WelcomeUser", resourceCulture);
            }
        }
    }
}
